<a href="https://colab.research.google.com/github/annakorotkova/NLP_finetuning/blob/master/GLUE_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

# Get the GPU device name.
device_name = tf.test.gpu_device_name()

# The device name should look like the following:
if device_name == '/device:GPU:0':
    print('Found GPU at: {}'.format(device_name))
else:
    raise SystemError('GPU device not found')

SystemError: ignored

In [0]:
import torch

# If there's a GPU available...
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

In [0]:
!pip install transformers

     |████████████████████████████████| 665kB 5.0MB/s 
     |████████████████████████████████| 1.1MB 24.2MB/s 
     |████████████████████████████████| 890kB 40.5MB/s 
     |████████████████████████████████| 3.8MB 45.4MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=629c23e7cbd858787d61b5959d31db160e91640ae0b0c1ef2cd2e5d0243eceed
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


Download datasets

In [0]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
load_data = drive.CreateFile({'id':'1AlbO4pMgbCAZO2XyGyKXsdWszyj-xMHx'})
finetuning = drive.CreateFile({'id':'1GyndnqvwF_yCCrr0cX8et7sbXGOeRuP5'})

In [0]:
# Loading GLUE datasets notebook
load_data.GetContentFile('Load_GLUE.ipynb')

# run Load_GLUE notebook
%run Load_GLUE.ipynb # this notebood downloads and extracts data

# BERT finetuning notebook
finetuning.GetContentFile('BERT_finetuning_function.ipynb') # this notebook contains the finetuning function

# run BERT_finetuning notebook
%run BERT_finetuning_function.ipynb

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive/
	Completed!
	Completed!
	Completed!
	Completed!
	Completed!
	Completed!
	Completed!
	Completed!
	Completed!
Processing MRPC...
	Completed!
	Completed!


SystemError: ignored

In [0]:
import pandas as pd

# names of respective datasets
data_names = ['CoLA', 'MNLI', 'MRPC', 'QNLI', 'QQP', 'RTE', 'SST-2', 'STS-B', 'WNLI']
# 'SNLI' also included, but not explicitly stated in GLUE benchmark --> not regarded until now


# define dictionary to save column names for each dataset
column_names = {}
# to store all datasets in one dict
datasets = {}

# Load the datasets into a pandas dataframe.
for i in data_names:
  # for CoLA dataset, column names need to be added
  if i == 'CoLA':
    datasets[i] = pd.read_csv("/content/drive/My Drive/Master Thesis/{0}/train.tsv".format(i), 
                    delimiter='\\t', quotechar='"', 
                    names=['sentence_source', 'label', 'label_notes', 'sentence'])
  else:
    datasets[i] = pd.read_csv("/content/drive/My Drive/Master Thesis/{0}/train.tsv".format(i), 
                    delimiter = '\\t', quotechar = '"')
  # Report the number of sentences.
  print('Number of training sentences: {:,}\n'.format(datasets[i].shape[0]))
  # Display 5 random rows from the data.
  print(datasets[i].sample(10))
  # save column names for each dataset in dict
  column_names[i] = datasets[i].columns

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.


Number of training sentences: 8,551

     sentence_source  ...                                           sentence
7446           sks13  ...                      Mary thinks for Bill to come.
2298            l-93  ...     I whipped the eggs from a puddle into a froth.
171             cj99  ...  The more obnoxious Fred, the less attention yo...
2861            l-93  ...               Carol carved the tree on the branch.
8360            ad03  ...  When dining with evil crocodiles, it is advisa...
5500            b_73  ...  You have presented so elegant a solution that ...
6521            g_81  ...     The man who I think that chased Fido returned.
2689            l-93  ...                        Amanda carried the package.
2453            l-93  ...                There ran a little boy in the yard.
102             cj99  ...    As you eat more, you want correspondingly less.

[10 rows x 4 columns]
Number of training sentences: 392,702

         index  promptID  ...         label1     gold_

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.


Number of training sentences: 104,743

         index  ...           label
56370    56370  ...  not_entailment
101810  101810  ...  not_entailment
16081    16081  ...      entailment
9716      9716  ...      entailment
11870    11870  ...      entailment
60127    60127  ...  not_entailment
29830    29830  ...      entailment
63362    63362  ...  not_entailment
72160    72160  ...      entailment
73708    73708  ...  not_entailment

[10 rows x 4 columns]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.


Number of training sentences: 363,870

            id  ... is_duplicate
296309  286902  ...          1.0
182349  100679  ...          1.0
96075   337516  ...          1.0
180524   50066  ...          1.0
190529   29163  ...          1.0
87023   266090  ...          0.0
268851  197063  ...          1.0
17399   257439  ...          0.0
198613  386782  ...          0.0
262981  273433  ...          1.0

[10 rows x 6 columns]
Number of training sentences: 2,490

      index  ...           label
1478   1478  ...      entailment
2055   2055  ...      entailment
1357   1357  ...      entailment
20       20  ...  not_entailment
549     549  ...  not_entailment
1784   1784  ...      entailment
1950   1950  ...  not_entailment
1882   1882  ...      entailment
1232   1232  ...      entailment
925     925  ...  not_entailment

[10 rows x 4 columns]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.


Number of training sentences: 67,349

                                                sentence  label
15807               movies , television and the theater       1
20989  have been worth cheering as a breakthrough but...      0
59549  is n't that stealing harvard is a horrible mov...      0
60720                                               old       0
38214                                serenity and poise       1
61255  he probably would n't be too crazy with his gr...      0
35708                           without being memorable       0
44360                 overflows with wisdom and emotion       1
9155                    israeli/palestinian conflict as       1
54455  allen shows he can outgag any of those young w...      1
Number of training sentences: 5,749

      index  ... score
1437   1437  ...  3.80
4431   4431  ...  3.40
3098   3098  ...  3.25
760     760  ...  0.00
304     304  ...  1.00
5571   5571  ...  3.00
1496   1496  ...  2.00
2236   2236  ...  3.10
1958   1958  .

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.


In [0]:
# print key & values of dictionary 'datasets'
# for key, value in datasets.items():
#    print (key, value)

# save colnames of respective datasets in dictionary
colnames = {}
for i in data_names:
    colnames[i] = datasets[i].columns.values

print(colnames)

{'CoLA': array(['sentence_source', 'label', 'label_notes', 'sentence'],
      dtype=object), 'MNLI': array(['index', 'promptID', 'pairID', 'genre', 'sentence1_binary_parse',
       'sentence2_binary_parse', 'sentence1_parse', 'sentence2_parse',
       'sentence1', 'sentence2', 'label1', 'gold_label'], dtype=object), 'MRPC': array(['Quality'], dtype=object), 'QNLI': array(['index', 'question', 'sentence', 'label'], dtype=object), 'QQP': array(['id', 'qid1', 'qid2', 'question1', 'question2', 'is_duplicate'],
      dtype=object), 'RTE': array(['index', 'sentence1', 'sentence2', 'label'], dtype=object), 'SST-2': array(['sentence', 'label'], dtype=object), 'STS-B': array(['index', 'genre', 'filename', 'year', 'old_index', 'source1',
       'source2', 'sentence1', 'sentence2', 'score'], dtype=object), 'WNLI': array(['index', 'sentence1', 'sentence2', 'label'], dtype=object)}


In [0]:
# print all possible values of labels
for i in data_names:
  for j in range(0, len(datasets[i].columns.values)):
    if datasets[i].columns.values[j] == 'label':
      print(i + " labels contain following possible values of labels: ")
      print(pd.unique(datasets[i].label)) 
    elif datasets[i].columns.values[j] == 'gold_label':
      print(i + " labels (gold_label) contain following possible values of labels: ")
      print(pd.unique(datasets[i].gold_label)) 
    elif datasets[i].columns.values[j] == 'is_duplicate':
      print(i + " labels (is_duplicate) contain following possible values of labels: ")
      print(pd.unique(datasets[i].is_duplicate)) 
 
# unique values of labels: [0 1] and ['not_entailment' 'entailment']
# unique values of gold_label (MNLI): ['neutral' 'entailment' 'contradiction']
# unique values of is_duplicate (QQP): [ 0.  1. nan]

CoLA labels contain following possible values of labels: 
[1 0]
MNLI labels (gold_label) contain following possible values of labels: 
['neutral' 'entailment' 'contradiction']
QNLI labels contain following possible values of labels: 
['not_entailment' 'entailment']
QQP labels (is_duplicate) contain following possible values of labels: 
[ 0.  1. nan]
RTE labels contain following possible values of labels: 
['not_entailment' 'entailment']
SST-2 labels contain following possible values of labels: 
[0 1]
WNLI labels contain following possible values of labels: 
[1 0]


In [0]:
import numpy as np

# modifying labels for MNLI, QNLI and RTE (before: string labels), 
# so that the model can work with them (model cannot work with strings)
labels = {}
mnli_qnli_rte = ['MNLI', 'QNLI', 'RTE']

#### Encode labels that have string values as int values, so that the model can
#### cope with it

# create empty ndarrays for QNLI and RTE labels
for i in mnli_qnli_rte:
  # for each colums in respective datasets
  for j in range(0, len(datasets[i].columns.values)):
    if datasets[i].columns.values[j] == 'label':
      labels[i] = np.empty(shape=datasets[i].shape[0], dtype = int, order='C')
        # check if the lengths of the empty arrays equal lengths of the respective datasets
    elif datasets[i].columns.values[j] == 'gold_label':
      labels[i] = np.empty(shape=datasets[i].shape[0], dtype = int, order='C')
  print(len(labels[i]) == datasets[i].shape[0])  # output: TRUE

# encode labels for MNLI, QNLI and RTE
for i in mnli_qnli_rte:
  # for each colums in respective datasets
  for j in range(0, len(datasets[i].columns.values)):
    counter = 0
    # for column 'label'
    if datasets[i].columns.values[j] == 'label':
      # for each label in label (for QNLI & RTE)
      for label in datasets[i].label:
        # encode 'not_entailment' as 0 (for MNLI)
        if label == 'not_entailment':
          labels[i][counter] = 0
        # encode 'entailment' as 1
        elif label == 'entailment':
          labels[i][counter] = 1
        counter += 1
    elif datasets[i].columns.values[j] == 'gold_label':
      # for each label in gold_label
      for label in datasets[i].gold_label:
        # encode 'neutral' as 0
        if label == 'neutral':
          labels[i][counter] = 0
        # encode 'entailment' as 1
        elif label == 'entailment':
          labels[i][counter] = 1
        # encode 'contradiction' as -1
        elif label == 'contradiction':
          labels[i][counter] = -1
        counter += 1
  # print unique labels and respective count of each unique label
  print(np.unique(labels[i], return_counts=True))

# add new column to dataset (with coded labels)
for i in mnli_qnli_rte:
  datasets[i]['coded_lables'] = labels[i]
  print(np.unique(datasets[i].coded_lables))
  print(datasets[i].sample(5))

True
True
True
(array([-1,  0,  1]), array([130903, 130900, 130899]))
(array([0, 1]), array([52366, 52377]))
(array([0, 1]), array([1241, 1249]))
[-1  0  1]
         index  promptID   pairID  ...         label1     gold_label coded_lables
114029  114029    107632  107632n  ...        neutral        neutral            0
234829  234829    110779  110779c  ...  contradiction  contradiction           -1
386750  386750     65180   65180n  ...        neutral        neutral            0
322069  322069     74271   74271e  ...     entailment     entailment            1
295631  295631     88242   88242e  ...     entailment     entailment            1

[5 rows x 13 columns]
[0 1]
         index  ... coded_lables
101443  101443  ...            1
96053    96053  ...            1
52          52  ...            0
51521    51521  ...            0
23454    23454  ...            0

[5 rows x 5 columns]
[0 1]
      index  ... coded_lables
2347   2347  ...            1
360     360  ...            1
1218  

In [0]:
# extract the sentences & labels of training set as numpy ndarrays

# print colnames of respective datasets (defines earlier) to find out which datasets
# contain sentence1, etc.
for key, values in colnames:
    if 'sentence1' in colnames[key]:
      print(key)
  # don't need an argument because the dictionary datasets is implemented as default


# Get the lists of sentences and their labels.
sentence1={}
for i in data_names:
  for j in range(0, len(datasets[i].columns.values)):
    if datasets[i].columns.values[j] == 'sentence1':
      sentence1["{0}_sentence1".format(i.lower)] = datasets[i].sentence1.values        

#print(type(sentence1[i]))
######
# extract the sentences & labels of training set as numpy ndarrays
#import numpy as np

# Get the lists of sentences and their labels.
#sentence_one = rte.sentence1.values
#sentence_two = rte.sentence2.values
#labels = rte.coded_labels.values

AttributeError: ignored